name: Monitoring Scheduler
on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - 'master'
  schedule:
    - cron: '*/ * * * *'
env:
  GITHUB_PAGES_PATH: http://itinao.github.io/web-performance-monitor
jobs:
  lighthouse:
    name: runner / lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Install lighthouse
        run: sudo npm i -g lighthouse
      - name: Run lighthouse
        run: |
          current_day=`TZ='Asia/Tokyo' date +%Y%m%d`
          current_datetime=`TZ='Asia/Tokyo' date +%H%M%S`
          save_dir=./public/${current_day}/${current_datetime}
          echo ::set-env name=CURRENT_DAY::$(echo $current_day)
          echo ::set-env name=CURRENT_DATETIME::$(echo $current_datetime)
          mkdir -p ${save_dir}
          lighthouse \
            --chrome-flags="--headless" \
            --output html \
            --emulated-form-factor desktop \
            --throttling-method provided \
            --output-path ${save_dir}/top_report.html \
            ${{ secrets.PAGE1 }}
          lighthouse \
            --chrome-flags="--headless" \
            --output html \
            --emulated-form-factor desktop \
            --throttling-method provided \
            --output-path ${save_dir}/search_report.html \
            ${{ secrets.PAGE2 }}
          lighthouse \
            --chrome-flags="--headless" \
            --output html \
            --emulated-form-factor desktop \
            --throttling-method provided \
            --output-path ${save_dir}/item_report.html \
            ${{ secrets.PAGE3 }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "URLはこっち！↓ \n ■ TOPページ \n ${{ env.GITHUB_PAGES_PATH }}/${{ env.CURRENT_DAY }}/${{ env.CURRENT_DATETIME }}/top_report.html \n ■ 検索ページ \n ${{ env.GITHUB_PAGES_PATH }}/${{ env.CURRENT_DAY }}/${{ env.CURRENT_DATETIME }}/search_report.html \n ■ 商品ページ \n ${{ env.GITHUB_PAGES_PATH }}/${{ env.CURRENT_DAY }}/${{ env.CURRENT_DATETIME }}/item_report.html"
          SLACK_TITLE: 計測結果だよ！
          SLACK_USERNAME: 計測くん
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
